### ISSUE TITLE
Access to single axis value

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_LIS3DH#12]
This mainly comes up in conditionals, and can currently be done like this:
```python
if lis3dh.acceleration[2] > SOME_VALUE:
    print("Z axis exceeds the value!")
```
but requires knowing the index of the axis. Is there anyway this could be done where it's more obvious what's being accessed?
Like this:
```python
if lis3dh.acceleration['Z'] > SOME_VALUE:
    print("Z axis exceeds the value!")
```
or this:
```python
if lis3dh.acceleration.Z > SOME_VALUE:
    print("Z axis exceeds the value!")
```

**Comment by dhalbert** [comment]
We could use `ucollections.namedtuple()`: http://circuitpython.readthedocs.io/en/2.x/docs/library/ucollections.html

Note that we are planning to rename all the `u...` modules eventually and make sure they match or are a subset of the CPython equivalents.

**Comment by caternuson** [comment]
Another use case:
```python
# Wait for LIS3DH to be flipped over
while lis3dh.acceleration[2] > 0:
    pass # do nothing
```

**Comment by Sigafoos** [comment]
Would it be better to have `lisd3h.acceleration.z`?

**Comment by tannewt** [comment]
Someone want to switch this to a named tuple and update the design guide?

**Comment by Sigafoos** [comment]
I can!
