### ISSUE TITLE
spinner_advanced memory allocation failed with Adafruit CircuitPython 1.0.0-rc.1

### ISSUE THREAD

**Issue by dglaude** [adafruit/Adafruit_CircuitPython_LIS3DH#2]
Using Adafruit CircuitPython 1.0.0-rc.1 and release 0.1.1 f9f906b
example spinner_advanced fail on memory allocation:

>>> import spinner_advanced
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "spinner_advanced.py", line 227, in <module>
MemoryError: memory allocation failed, allocating 376 bytes

Just trying to follow the https://www.youtube.com/watch?v=Qms1_QSdj6I

**Comment by tannewt** [comment]
How are you loading the file? AMPY or through the USB drive?

**Comment by dglaude** [comment]
Certainly not AMPY. Copy of file on USB from OSX.

2017-06-21 2:27 GMT+02:00 Scott Shawcroft <notifications@github.com>:

**Comment by jerryneedell** [comment]
I had the same problem if I tried to import the spinner_advanced example. The tutorial has it renamed to main.py to run at boot and that seems to be just enough memory allocation difference to allow it to fit. I tried removing a bit of the code and am now able to run it via import. 
I removed the "smooth animation" just to see if it would work.

**Comment by dglaude** [comment]
Thanks, now working for me as main.py.
That memory limitation is really an annoyance.

2017-06-21 15:28 GMT+02:00 jerryneedell <notifications@github.com>:

**Comment by tannewt** [comment]
Yup! Memory is tight on the device.

Another way to minimize memory use on import is to run it through mpy-cross. That will pack it into byte code which takes less memory to load.
