### ISSUE TITLE
Issue with neopixel.py

### ISSUE THREAD

**Issue by rileywiley** [adafruit/Adafruit_CircuitPython_LIS3DH#35]
Hi, 

I am currently able to use the neopixel library and the LIS3DH libraries independently. But I try to import both libraries into a single file, the program breaks and will not run. Leaving all the referenced code and removing the import adafruit_lis3dh, will allow to program to run without input from the lis3dh. Any thoughts on why this might be?

**Comment by caternuson** [comment]
Please ask this in the forums:
https://forums.adafruit.com/viewforum.php?f=60
