### ISSUE TITLE
lis3dh.tapped returning multiple True on I2C, not responding at all on SPI

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_LIS3DH#40]
The `tap.py` example doesn't work as it was. I've updated it to remove the SPI hardware setup, and added a `time.sleep()`. It works for now, but the odd behavior needs to be addressed directly.

Without the `time.sleep()`, it returned `True` twice for every tap or double-tap detected. Tap works successfully in the `cpx Express` lib, but there's so much going on there, it may be acting like a debounce behind the scenes. There are three other parameters that can be set for `set_tap` which are set in the `cpx` lib, and may be able to resolve the multiple tap-return issue.

I haven't looked at the datasheet but I'm wondering if it's possible that tap isn't implemented for SPI. If I set the threshold really low, it returns True then False once on reload, but never in response to tapping.

**Comment by ladyada** [comment]
i think this got resolved by adding the IRQ pin?

**Comment by kattni** [comment]
It looks like it did. I had someone else test I2C and SPI as well. Closing this issue.
