### ISSUE TITLE
Small INT overflow on Halowing_m0

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_LIS3DH#67]
With current tip of main CP installed on a Hallowing_m0  __init__ fails:
```
Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 6.2.0-beta.1-23-g0c0b51711 on 2021-02-01; HalloWing M0 Express with samd21g18
>>> import lis3dh_simpletest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lis3dh_simpletest.py", line 16, in <module>
  File "adafruit_lis3dh.py", line 332, in __init__
OverflowError: small int overflow
>>> 
```

**Comment by ladyada** [comment]
@jerryneedell kinda weird, that line is the i2c initialor??

**Comment by jerryneedell** [comment]
> @jerryneedell kinda weird, that line is the i2c initialor??

Agreed!

**Comment by ladyada** [comment]
wanna try tracking down?

**Comment by jerryneedell** [comment]
sure -- just pulling out my breakout and some other boards to examine.

**Comment by jerryneedell** [comment]
Works OK on a qtpy_m0_haxpress...

**Comment by jerryneedell** [comment]
hmmm -- maybe related to this https://github.com/adafruit/circuitpython/blame/main/ports/atmel-samd/boards/hallowing_m0_express/mpconfigboard.mk#L12 ...  added about 6 months ago though -- I'll try some tests

**Comment by jerryneedell** [comment]
Yes -- changing 
LONGINT_IMPL = NONE
to
LONGINT_IMPL = MPZ

fixes it, BUT it won't fit in flash -- I had to remove pulseio to test it.

Now to find out why this makes a difference. Is I2C broken on any board that has 
LONGINT_IMPL = NONE
That is a lot of boards....

**Comment by jerryneedell** [comment]
ruh roh...
It looks like an issue with the native busdevice
I build with CIRCUITPY_BUSDEVICE = 0
an use the Adafruit_BusDevice Library it works OK
... I'll file an issue in the CP repo

**Comment by ladyada** [comment]
oi good find!@

**Comment by tannewt** [comment]
Closing in favor of https://github.com/adafruit/circuitpython/issues/4109
